name: EasierBackup
version: ${project.version}
api-version: 1.13
author: MisterMel
main: tech.mistermel.easierbackup.EasierBackup
commands:
  easierbackup:
    description: Main command
    aliases: ['backup']
